version: '3.8'

services:
  vvs-backend:
    build: ./backend
    container_name: vvs_backend
    ports:
      - "9601:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=${DB_HOST} 
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - ./backend:/app
    networks:
      - camo_network
      
  vvs-frontend:
    image: nginx:alpine
    container_name: vvs_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9600:80"
    networks:
      - camo_network
    depends_on:
      - vvs-backend

networks:
  camo_network:
    driver: bridge